# Generated by Django 5.1.6 on 2025-08-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='nacionalidad',
        ),
    ]
